### ISSUE TITLE
`unidist[mpi]` can't be installed by pip for python 3.11

### ISSUE THREAD

**Issue by anmyachev** [modin-project/unidist#334] opened 2023-09-07 16:35 UTC
Logs:
```bash
ERROR: Cannot install unidist[mpi]==0.2.1, unidist[mpi]==0.2.2, unidist[mpi]==0.3.0, unidist[mpi]==0.4.0 and unidist[mpi]==0.4.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    unidist[mpi] 0.4.1 depends on mpi4py-mpich; extra == "mpi"
    unidist[mpi] 0.4.0 depends on mpi4py-mpich; extra == "mpi"
    unidist[mpi] 0.3.0 depends on mpi4py-mpich; extra == "mpi"
    unidist[mpi] 0.2.2 depends on mpi4py-mpich; extra == "mpi"
    unidist[mpi] 0.2.1 depends on mpi4py-mpich; extra == "mpi"
```

It's worth noting that https://anaconda.org/conda-forge/unidist-mpi can be installed using conda (according to successfull builds in https://github.com/conda-forge/modin-feedstock/pull/92).

cc @YarShev 

**UPD**: looks like unidist-mpi doesn't work correctly when installing through conda under python 3.11
Logs:
```bash
Run MODIN_BENCHMARK_MODE=True mpiexec -n 1 -genv AWS_ACCESS_KEY_ID foobar_key -genv AWS_SECRET_ACCESS_KEY foobar_secret python -m pytest modin/pandas/test/internals/test_benchmark_mode.py
mpiexec: Error: unknown option "-genv"  # <- the problem is the difference between mpich vs openmpi distributions of mpi
```

Dependencies:
```bash
Under python 3.9:
    + mpi                                          1.0  mpich                conda-forge/linux-64     Cached
    + mpi4py                                     3.1.4  py39h32b9844_0       conda-forge/linux-64     Cached
    + mpich                                      4.1.2  h846660c_100     

Under python 3.11
    + mpi                                          1.0  openmpi              conda-forge/linux-64        4kB
    + mpi4py                                     3.1.4  py311hd0725ac_0      conda-forge/linux-64      657kB
    + openmpi                                    4.1.5  h414af15_101         conda-forge/linux-64        4MB
```

**Comment by YarShev** [comment] 2023-09-08 12:07
@anmyachev,

`unidist-mpi` from conda should work with py 3.11. The issue you are seeing is that for py 3.9 mpich is installed, whereas for py 3.11 openmpi is installed. openmpi has the parameters for mpiexec command that are different from mpich's mpiexec. To fix the issue you should use [-x](https://www.open-mpi.org/doc/v3.0/man1/mpiexec.1.php#:~:text=%2D-,x%20%3Cenv%3E,-Export%20the%20specified) to pass an env var to the executable.

`unidist[mpi]` from PyPI doesn't work with py 3.11 because `unidist[mpi]` depends on `mpi4py-mpich` package that doesn't have a build for py 3.11. Actually, `mpi4py-mpich` is a very old package and is not supported properly by maintainers who pushed the package. We plan to get rid of it in the next minor release 0.5.0.

**Comment by anmyachev** [comment] 2023-09-08 13:46
> unidist-mpi from conda should work with py 3.11. The issue you are seeing is that for py 3.9 mpich is installed, whereas for py 3.11 openmpi is installed. openmpi has the parameters for mpiexec command that are different from mpich's mpiexec. To fix the issue you should use [-x](https://www.open-mpi.org/doc/v3.0/man1/mpiexec.1.php#:~:text=%2D-,x%20%3Cenv%3E,-Export%20the%20specified) to pass an env var to the executable.

@YarShev the problem is that this is not the expected behavior. A user can have code that does not expect another implementation of the standard to be installed (such as in Modin when using a different version of python).

**Comment by anmyachev** [comment] 2023-09-11 17:04
@YarShev FYI: the same problem with python 3.10.

**Comment by anmyachev** [comment] 2023-09-11 20:05
@YarShev [openmpi](https://github.com/modin-project/modin/actions/runs/6149658180/job/16687741351?pr=6548) doesn't work out of the box:
```bash
_____________________________ test_turn_off[False] _____________________________

set_benchmark_mode = None

    @pytest.mark.parametrize("set_benchmark_mode", [False], indirect=True)
    def test_turn_off(set_benchmark_mode):
>       df = pd.DataFrame([0])

modin/pandas/test/internals/test_benchmark_mode.py:52: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
modin/logging/logger_decorator.py:128: in run_and_log
    return obj(*args, **kwargs)
modin/pandas/dataframe.py:183: in __init__
    distributed_frame = from_non_pandas(data, index, columns, dtype)
modin/pandas/utils.py:71: in from_non_pandas
    new_qc = FactoryDispatcher.from_non_pandas(df, index, columns, dtype)
modin/core/execution/dispatching/factories/dispatcher.py:185: in from_non_pandas
    return cls.get_factory()._from_non_pandas(*args, **kwargs)
modin/core/execution/dispatching/factories/dispatcher.py:115: in get_factory
    Engine.subscribe(_update_engine)
modin/config/pubsub.py:217: in subscribe
    callback(cls)
modin/pandas/__init__.py:1[57](https://github.com/modin-project/modin/actions/runs/6149658180/job/16687741351?pr=6548#step:9:58): in _update_engine
    initialize_unidist()
modin/core/execution/unidist/common/utils.py:48: in initialize_unidist
    unidist.init()
/usr/share/miniconda3/envs/modin_on_unidist/lib/python3.10/site-packages/unidist/api.py:92: in init
    init_backend()
/usr/share/miniconda3/envs/modin_on_unidist/lib/python3.10/site-packages/unidist/core/base/utils.py:28: in init_backend
    initialize_mpi()
/usr/share/miniconda3/envs/modin_on_unidist/lib/python3.10/site-packages/unidist/core/backends/mpi/utils.py:12: in initialize_mpi
    init()
/usr/share/miniconda3/envs/modin_on_unidist/lib/python3.10/site-packages/unidist/core/backends/mpi/core/controller/api.py:195: in init
    intercomm = MPI.COMM_SELF.Spawn(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   mpi4py.MPI.Exception: MPI_ERR_SPAWN: could not spawn processes

mpi4py/MPI/Comm.pyx:1931: Exception
______________________________ test_turn_on[True] ______________________________

set_benchmark_mode = None

    @pytest.mark.parametrize("set_benchmark_mode", [True], indirect=True)
    def test_turn_on(set_benchmark_mode):
>       df = pd.DataFrame([0])

modin/pandas/test/internals/test_benchmark_mode.py:[60](https://github.com/modin-project/modin/actions/runs/6149658180/job/16687741351?pr=6548#step:9:61): 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
modin/logging/logger_decorator.py:128: in run_and_log
    return obj(*args, **kwargs)
modin/pandas/dataframe.py:183: in __init__
    distributed_frame = from_non_pandas(data, index, columns, dtype)
modin/pandas/utils.py:71: in from_non_pandas
    new_qc = FactoryDispatcher.from_non_pandas(df, index, columns, dtype)
modin/core/execution/dispatching/factories/dispatcher.py:185: in from_non_pandas
    return cls.get_factory()._from_non_pandas(*args, **kwargs)
modin/core/execution/dispatching/factories/dispatcher.py:115: in get_factory
    Engine.subscribe(_update_engine)
modin/config/pubsub.py:217: in subscribe
    callback(cls)
modin/pandas/__init__.py:157: in _update_engine
    initialize_unidist()
modin/core/execution/unidist/common/utils.py:48: in initialize_unidist
    unidist.init()
/usr/share/miniconda3/envs/modin_on_unidist/lib/python3.10/site-packages/unidist/api.py:92: in init
    init_backend()
/usr/share/miniconda3/envs/modin_on_unidist/lib/python3.10/site-packages/unidist/core/base/utils.py:28: in init_backend
    initialize_mpi()
/usr/share/miniconda3/envs/modin_on_unidist/lib/python3.10/site-packages/unidist/core/backends/mpi/utils.py:12: in initialize_mpi
    init()
/usr/share/miniconda3/envs/modin_on_unidist/lib/python3.10/site-packages/unidist/core/backends/mpi/core/controller/api.py:195: in init
    intercomm = MPI.COMM_SELF.Spawn(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   mpi4py.MPI.Exception: MPI_ERR_SPAWN: could not spawn processes
```

**Comment by YarShev** [comment] 2023-09-12 08:47
> @YarShev the problem is that this is not the expected behavior. A user can have code that does not expect another implementation of the standard to be installed (such as in Modin when using a different version of python).

You are right, we should explicitly say which MPI implementation goes with `unidist-mpi` by default (we already say that) and provide the stuff correctly (there is inconsistency). However, if the user wants to use other MPI implementation, he should be aware of the specifics of that implementation. What we can do for now is to make another build of unidist in conda-forge to provide unidist-mpi with mpich. I am pushing the things in https://github.com/conda-forge/unidist-packages-feedstock/pull/10. Let me know if the new build of unidist-mpi works for you. Nevertheless, we will most likely switch to openmpi installation in unidist 0.5.0.

**Comment by YarShev** [comment] 2023-09-13 07:30
Now, mpich is installed with unidist-mpi from conda-forge. Closing the issue. Feel free to reopen.

**Comment by anmyachev** [comment] 2023-09-13 09:57
@YarShev this issue is originally about pip. I assume that you didn’t do anything with the installation via pip, right?

**Comment by YarShev** [comment] 2023-09-13 12:29
As I said earlier, the issue is that `mpi4py-mpich` package that doesn't have a build for py 3.11. We plan to get rid of this dependency in 0.5.0.

**Comment by anmyachev** [comment] 2023-09-13 12:43
Ok, but why not leave a tracker(issue) about Python 3.11 support for unidist with mpi?

**Comment by YarShev** [comment] 2023-11-23 14:47
Closing this issue since as of 0.5.0 unidist can be installed with pip for python 3.11.

**Closed by YarShev** 2023-11-23 14:47 UTC
Labels: bug 🦗, P0, dependencies 🔗, MPI
